### PR TITLE
Updated faq.md

### PR DESCRIPTION
**Pull request by Picopin7374**

### CODE REVIEW

**Comment by larsenv** [comment]
What's the point of this?

**Comment by Peter0x44** [comment]
Don't we already have the dos and don'ts page? Why not simply write a paragraph linking it instead of repeating sections of it.

**Comment by Picopin7374** [comment]
Sure do

**Review by Picopin7374 — COMMENTED** [review]
Updated FAQ.MD per request

**Comment by Naim2000** [comment]
I think you want to start using branches for your pull requests. I don't think you want this to happen, been there, done that.
image

**Pull request closed without merging**
