### PR TITLE
Update info about USB Loader GX

### PR DESCRIPTION
**Pull request by Naim2000**
Thank you @wiidev :)

### CODE REVIEW

**Review by larsenv — CHANGES_REQUESTED** [review]
NTFS is supported by the Homebrew Channel. What's the point in mentioning WBFS if it isn't recommended?

**Comment by Naim2000** [comment]
> What's the point in mentioning WBFS if it isn't recommended?

To clear any confusion since it's an option to format in Wii backup manager. Might add that to the wii backup manager page

**Comment by Naim2000** [comment]
> NTFS is supported by the Homebrew Channel. 
No

**Comment by larsenv** [comment]
> > NTFS is supported by the Homebrew Channel.
> 
> No

Please prove that it isn't compatible. I swear that it is.

**Comment by thondorigithub1** [comment]
might have confused with usb loader gx as they support ntfs, _i think_

**Comment by Naim2000** [comment]
Can someone clear the pending reviewer and requested changes

**Comment by Snare-Hawk** [comment]
i forgot about this PR
my fault
skull emoji

**Pull request merged**
