### PR TITLE
Update Jekyll

### PR DESCRIPTION
**Pull request by spotlightishere**
The specified Jekyll version was extremely outdated, along with all plugins. Additionally, as of Ruby 3.0, `webrick` (used to provide the web server to locally `jekyll serve`) is no longer included with a standard Ruby install. All of these make the site quite difficult to work with by default without some effort.

I migrated away from a gemspec towards specifying versions within the Gemfile directly. I've additionally removed `jekyll-redirect-from` as it does not appear to be used anywhere within this site and was causing issues with Jekyll, alongside `bundler` and `rake` as they are most likely not needed. Lastly, I allow `Gemfile.lock` so the same version of these gems can be installed on other's installs.

### CODE REVIEW

**Comment by Peter0x44** [comment]
Thanks! I've been meaning to do this for a while, but you have saved me a lot of effort here.

**Comment by Peter0x44** [comment]
`Unable to find a spec satisfying nokogiri (>= 1.4) in the set. Perhaps the lockfile is corrupted? Found nokogiri (1.11.4-arm64-darwin) that did not match the current`
Although I'm having this pretty inexplicable issue when trying to run `bundle install`... I'm not using arm64 darwin, and there definitely is a 64 bit Linux version for nokogiri...

**Comment by spotlightishere** [comment]
Uh oh, forgot to catch that - thank you! You should be able to drop the `-arm64-darwin` from the locked version number and it'll install for the device's local architecture, just tested on an amd64 device

**Comment by Peter0x44** [comment]
Works for me, thanks!

**Pull request merged**
