### PR TITLE
Update riitag-wiiu for Aroma

### PR DESCRIPTION
**Pull request by osfanbuff63**
Updates the UTag page for Aroma, as it has [recently added support for it](https://github.com/RiiConnect24/UTag/pull/3).

Aroma is currently in public beta, [wiiu.hacks.guide](https://wiiu.hacks.guide) hasn't been updated yet (and there's no PR or issue open for it either), and the [guide to install](https://discord.com/channels/206934458954153984/258999527783137280/1017102235257282660) on [the Discord](https://discord.gg/rc24) is slightly incomplete regarding how to actually install the plugin and coldboot it, etc. In addition, I don't own a Wii U and it's likely there's no way I could get anything like this running on Cemu. So this PR is a draft until I get those sorted out.

More notes about Aroma can be found [here](https://maschell.github.io/homebrew/2022/09/05/aroma.html).

### CODE REVIEW

**Comment by Brawl345** [comment]
Thanks for the PR. I told Lars that I will look over it.

You should add somewhere that only Aroma is supported at the top. I don't think you have to describe how it's installed since it will be covered by wiiu.hacks.guide. I don't know when they will update it though... I have written one on [WiiDatabase.de](https://wiidatabase.de/wii-u-downloads/hacks/aroma/) but it's obviously in German and I don't think duplicating the instructions is a solution since it will be added to wiiu.hacks.guide (I hope).

For the section "`##### Section III - Running the plugin`" you could just remove everything and add "You don't need to manually run the plugin - just run Aroma and it will automatically be loaded. We recommend setting up Aroma for coldbooting so it the plugin gets loaded automatically when you boot the console" or something.

**Comment by Brawl345** [comment]
Looks god, can be merged now!

**Comment by Peter0x44** [comment]
Would it not be best to wait until wiiu.hacks.guide is updated before applying this?

**Comment by osfanbuff63** [comment]
> Would it not be best to wait until wiiu.hacks.guide is updated before applying this?

Possibly, but Tiramisu's installation process is pretty much the same as Aroma's, so I might just fork it and replace references to Tiramisu while changing links, etc when appropriate until it's merged into the main guide. idk though because I don't have a Wii U as mentioned multiple times before.

**Comment by larsenv** [comment]
I don't know why this never was merged. Let me do that.

**Comment by larsenv** [comment]
Had to commit it manually because of a merge conflict because of the gemfile

**Pull request closed without merging**
