### PR TITLE
Bluebomb does not work in ChromeOS

### PR DESCRIPTION
**Pull request by Devnol**
Idk why we hadn't added this before but we kept getting people using chromebooks for some reason and then I looked and realised we hadn't so here it is ig.

### CODE REVIEW

**Review by osfanbuff63 — APPROVED** [review]
I could write an outside wii.guide tutorial on how to get a LiveUSB working from a stock Chromebook - that's obviously not in scope here though.

**Comment by Snare-Hawk** [comment]
related #283 
i just fixed this up, i think at this point it's up to whoever can merge either PR to decide which one to merge
i don't personally care at this point lol

**Comment by Peter0x44** [comment]
Merged #283 so this shouldn't be necessary anymore

**Comment by Devnol** [comment]
Fine by me

**Pull request closed without merging**
