### PR TITLE
WiiLink24 Japanese Version

### PR DESCRIPTION
**Pull request by norenTM**
### Wow! This was a fun task.

As WiiLink24 concerns Japanese channels specifically, I thought that it would be a good idea to create a Japanese translation for the installation instructions page. This was not created with a translator, and done entirely by me! It is possible that there are sections that could be improved as I am not a native Japanese person, however my translation is certainly understandable and more clear than a machine translation of the English page.

If you have any questions, please contact me on Discord: `Noren#7588`.

### CODE REVIEW

**Comment by urmum-69** [comment]
Hi,
If you are interested in translating, you should do so through crowdin instead

**Comment by norenTM** [comment]
Sure I can do that.
I am disappointed however at the immediate dismissal of this translation, a lot of effort was put into this. Having no contribution for my work too is something that doesn't feel right with me - I'm making a contribution!

**Comment by InternalLoss** [comment]
Especially when it's a Japanese translation for a Japanese channel - I'd be tempted to re-open this.

**Comment by KcrPL** [comment]
> Sure I can do that.
> I am disappointed however at the immediate dismissal of this translation, a lot of effort was put into this. Having no contribution for my work too is something that doesn't feel right with me - I'm making a contribution!

We are unable to merge this PR as this would break our system that's synchronizing the translations between GitHub (wii.guide) and Crowdin (a platform used to translate stuff).

I'm sorry but if you want to contribute to this project, you have to do it through that site.

**Comment by InternalLoss** [comment]
> We are unable to merge this PR as this would break our system that's synchronizing the translations between GitHub (wii.guide) and Crowdin (a platform used to translate stuff).
> 
> I'm sorry but if you want to contribute to this project, you have to do it through that site.

That at least makes more sense.

**Comment by norenTM** [comment]
> > Sure I can do that.
> > I am disappointed however at the immediate dismissal of this translation, a lot of effort was put into this. Having no contribution for my work too is something that doesn't feel right with me - I'm making a contribution!
> 
> We are unable to merge this PR as this would break our system that's synchronizing the translations between GitHub (wii.guide) and Crowdin (a platform used to translate stuff).
> 
> I'm sorry but if you want to contribute to this project, you have to do it through that site.

Thank you for providing me with a valid answer! I am okay with this ^^

**Comment by norenTM** [comment]
image
The Crowdin page needs some fixes too, as a heads up

**Comment by KcrPL** [comment]
That's not an error or something like that. That's how we create the "table of contents" on the site.

**Comment by norenTM** [comment]
Then, what's the point of changing the string?
I think you might've interpreted that wrong, by me adding `目次` for table of contents, it doesn't like that I haven't kept the English title. I think that the string between the quotation marks should be the only part of the string being translated, it could potentially mess up the site.

**Comment by norenTM** [comment]
Could you guys maybe add something in the readme to make the use of Crowdin clear? Maybe then no more time would be wasted like this :P

**Comment by norenTM** [comment]
image
Here is another issue. Separating sentences assumes that all languages use English punctuation. In Japanese, punctuation marks (eg. 「」、。) include spaces within the one character - adding a unremovable halfwidth space makes the gap unusually large.  It  would  look  like  this  for  a  Japanese  reader.

**Comment by KcrPL** [comment]
Shouldn't matter, right?

**Comment by norenTM** [comment]
I am very sorry - this Crowdin page is awful. I don't feel like my concerns have been listened to either, it can be seen that this page was not created by someone with translating experience. I have done about 35% of the translation which was 100% complete on this PR. I am not going to finish it, feel free to waste time copying and pasting like I have been.

I just wanted to help out, and my help is obviously wanted. I apologise for the intensity of my messages, the replies I have been receiving have been very short and do not address any concerns I have made.

**Comment by KcrPL** [comment]
> Could you guys maybe add something in the readme to make the use of Crowdin clear? Maybe then no more time would be wasted like this :P

Added in [de2ad38](https://github.com/RiiConnect24/Wii-Guide/commit/de2ad38e3be0d9d5a40e52bad07bc5865ca028f8)

**Comment by Artuto** [comment]
>>> it can be seen that this page was not created by someone with translating experience.

Crowding is not only used by us. It's used by thousands of projects, if it was that awful nobody would use it.

>>> the replies I have been receiving have been very short and do not address any concerns I have made.

None of us speak Japanese so we can't really help you with a thing like punctuation.

That's just my 2 cents.

**Comment by KcrPL** [comment]
> I am very sorry - this Crowdin page is awful. I don't feel like my concerns have been listened to either, it can be seen that this page was not created by someone with translating experience. I have done about 35% of the translation which was 100% complete on this PR. I am not going to finish it, feel free to waste time copying and pasting like I have been.
> 
> I just wanted to help out, and my help is obviously wanted. I apologise for the intensity of my messages, the replies I have been receiving have been very short and do not address any concerns I have made.

Unfortunately, I'm not able to help you with this. In order to enable a translation on the site, we need a full translation. Crowdin is a widely used site for managing translations, I can't really help you with anything Crowdin related. Translating requires time. However, thank you for your time and interest :)

**Comment by norenTM** [comment]
> In order to enable a translation on the site, we need a full translation. Crowdin is a widely used site for managing translations, I can't really help you with anything Crowdin related. Translating requires time.

This is correct. However, I have used Crowdin before, you can select parts of a file to be translated. It'd be best to
- Not require translations for code strings like `{: .notice--warning}`
- Allow whole paragraphs to be edited, for punctuation issues. (Not all languages are English, this is basic translation).

If you guys were serious about this, the Crowdin page would have been set up better. And, the 100% completed translation I have provided would have been accepted - the readme didn't reflect the criteria at the time.

Please be more careful with the way translations are managed as a group, it's very unprofessional like this.

Again, the translation I have provided is complete - feel free to use it.

**Comment by KcrPL** [comment]
Well, your translation is only for WiiLink24.

**Comment by norenTM** [comment]
> > it can be seen that this page was not created by someone with translating experience.
> 
> Crowding is not only used by us. It's used by thousands of projects, if it was that awful nobody would use it.
> 
> > the replies I have been receiving have been very short and do not address any concerns I have made.
> 
> None of us speak Japanese so we can't really help you with a thing like punctuation.
> 
> That's just my 2 cents.

I am saying that the way the Crowdin page was set up is awful - the software is great, I have used it numerous times in the past.

You do not need to help me with Japanese punctuation - I have literally finished it. I am saying that you should not have spaces as UNEDITABLE strings, halfwidth spaces DO NOT exist in Japanese at all. They need to be removed from the translation (as they have been in my PR), the current configuration doesn't allow this.

**Comment by norenTM** [comment]
> Well, your translation is only for WiiLink24.

This is very correct. This is also very evident of how RiiConnect24 thinks of translation contributions, they do not care. That is why I ceased translating.

I started with WiiLink24 as it focuses on Japanese applications, I thought that Japanese people could have benefited from this translation. However, RiiConnect24 seems not to think so. I am shocked at this argument aimed at me as a person, translation is a group effort, especially with an open-source project.

**Comment by Artuto** [comment]
If we did not care about translations like you say this could have been closed without any comment.

This conversation is useless.

**Comment by KcrPL** [comment]
`I am shocked at this argument aimed at me as a person` I think you're little crazy.

What do you not understand about the first answer that I sent? 
>We are unable to merge this PR as this would break our system that's synchronizing the translations between GitHub (wii.guide) and Crowdin (a platform used to translate stuff).

If you want to contribute, you're more than welcome to do that on Crowdin.

**Comment by urmum-69** [comment]
Just to be totally clear, closing this PR is not an exception
see #137 
This is not a personal attack of you - that's just how we handle things

**Pull request closed without merging**
