### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by larsenv**

### CODE REVIEW

**Comment by CommandBlock6417** [comment]
Larsen, the pictures aren't added in some, if not all of the translations. Check hbb.md (Greek) for example. Why is it missing the icon line?

**Comment by dhtdht020** [comment]
> Larsen, the pictures aren't added in some, if not all of the translations. Check hbb.md (Greek) for example. Why is it missing the icon line?
> 

That crowdin was a bad idea

**Comment by larsenv** [comment]
I removed the pic for the hbb page earlier because it had a picture of the Homebrew Channel logo, not the Homebrew Browser logo. So that one is intended.

**Comment by larsenv** [comment]
Wheeee time to squash and merge this bad boy

**Pull request merged**
