### PR TITLE
Delete Gemfile.lock

### PR DESCRIPTION
**Pull request by TheShadowEevee**
This file doesn't need to be in the repository and is creating some conflicts primarily when running Jekyll on Windows. It's best to let each machine generate this automatically.

### CODE REVIEW

**Comment by Peter0x44** [comment]
Perhaps add it to the gitignore so one can add it by accident?

**Comment by TheShadowEevee** [comment]
It is in there already, it just had to be `git rm`'ed

**Comment by Peter0x44** [comment]
Ah okay, my bad
LGTM then

**Comment by Snare-Hawk** [comment]
THE BEST PR I'VE EVER SEEN

**Pull request merged**
