### PR TITLE
Website Cleanup

### PR DESCRIPTION
**Pull request by NightYoshi370**
Dynamic footer links

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Actually, don't merge this PR just yet. I'd like to do a few more renovations

**Comment by NightYoshi370** [comment]
Alright, I think I'm complete for now. I guess if there is something more I can do, let me know.
It's time for review

**Comment by NightYoshi370** [comment]
Alright, in my latest commit, I merge the three dump games pages into one. There's already the table of contents to act like an index so there is really no point of a page index.
I'm gonna do the same for the Homebrew Channel install page to make it similar to the Unlaunch install page in the DSi hacking guide

**Comment by larsenv** [comment]
Thanks.

**Pull request merged**
