### PR TITLE
added-emulated-gc-saves-guide

### PR DESCRIPTION
**Pull request by playerjmr**
added some guides to make emulated memory cards and also fixed a typo in one of the guides

### CODE REVIEW

**Comment by playerjmr** [comment]
oh, you're combining ALL of the save pages together?

**Comment by Naim2000** [comment]
that's what i want to do yeah

**Comment by playerjmr** [comment]
my apologies, i had misunderstood and thought you were just making a wii/vwii saves page. doesnt that seem like a lot to have on one page though? the reason i wanted them seperate was because sometimes just gamecube people will need the page for booting into swiss and whatnot.

**Comment by Naim2000** [comment]
It would be a lot to have on one page. Which is why i added buttons there

**Comment by playerjmr** [comment]
i see. i suppose that is fine then. feel free to use parts of my gcsaves page for the guide if you would like. i have some other ideas for potential pages i could work on instead. shall i just close this draft pr then?

**Comment by Naim2000** [comment]
Sad conclusion but. Yeah

**Pull request closed without merging**
