### PR TITLE
Update patcher links again

### PR DESCRIPTION
**Pull request by Leseratte10**
Welp, needed to update the patchers again because of a bug, so here are the new links again.

### CODE REVIEW

**Comment by SketchMaster2001** [comment]
R.I.P KcrPL

**Comment by urmum-69** [comment]
is it possible for you just to provide a link to the latest always, so it doesn't have to be continually updated?

**Comment by Leseratte10** [comment]
That might not be the worst idea. I'll talk to Wiimm and see if we can add something like that.

**Comment by KcrPL** [comment]
I'm working on an update to the RiiConnect24 Patcher.

**Pull request merged**
