### PR TITLE
Swap ios4249 and ios250 in themes

### PR DESCRIPTION
**Pull request by Naim2000**
image

### CODE REVIEW

**Comment by larsenv** [comment]
Why?

**Comment by Naim2000** [comment]
Because d2x base 56 is installed to IOS250 now

**Comment by Naim2000** [comment]
image

**Comment by larsenv** [comment]
I foolishly merged this then realized that I believe IOS250 was working better for installing themes. Not 100% sure. Now that the base of IOS250 is installed to IOS249, this change is unnecessary.

**Comment by Naim2000** [comment]
Yeah so apparently the crash was just comically timed and has nothing to do with the fact that it's base 57

**Pull request merged**
