### PR TITLE
Concerns about bias on wii.guide [DO NOT MERGE!]

### PR DESCRIPTION
**Pull request by emilydaemon**
Since there is no issues page on this repository, I'm going to put this here.
I am very concerned about the bias on the guide. It feels like an advertisement for RiiConnect24.
In addition to concerns recently brought up by WiiLink, the Wii-Guide repository is currently owned by the RiiConnect24 organization on GitHub. This is very worrying, as wii.guide is meant to be a bias-free Wii guide, not a RiiConnect24 guide.
I think wii.guide should have its own organization, with playerjmr or Naim2000 (also known as thepikachugamer) as the owner.
Ideally, Larsenv wouldn't be a member of this organization due to controversy, and to keep the guide as bias-free as possible, as Larsenv is the owner of RiiConnect24.

### CODE REVIEW

**Comment by KCRTR3** [comment]
i totally agree, as i read the pdf and i really didnt think that larsen could DOX a person, he really crossed the line, IMO

**Comment by Peter0x44** [comment]
In fairness, he didn't do a meaningful dox
Not trying to defend, but it's not like he published an address or IP, it was all sent in dms.

**Comment by larsenv** [comment]
I'm trying to figure out what's the best option, as I don't want the guide to be biased like they claimed I was, I had wanted to just have WiiLink's guide be redirected to their website because they have a copy of the guide there. I had pinged Sketch regarding that and he didn't respond. Wii.guide was never supposed to be an advertisement for RiiConnect24, even though it kind of seemed that way. We've been called out for this 5 years ago.

**Comment by playerjmr** [comment]
We had put the wiilink discord on that guide that nova wrote, but then you reverted the entire thing. Kind of sends a distasteful message

**Comment by InvalityEC** [comment]
I remember reading the guide again earlier this year when I was soft modding my new Wii and a it was pretty biased, I'm pretty sure it directs you to install RC24 after you do homebrew, but I might be wrong I'm not sure. Mainly came across as if there is only RC24 and no others

**Comment by larsenv** [comment]
> We had put the wiilink discord on that guide that nova wrote, but then you reverted the entire thing. Kind of sends a distasteful message

I explained why I reverted it but as I've said I'm thinking of just linking WiiLink's page for the people which are intending to install it rather than make our own page, but I created a group DM to be sorting it out.

**Comment by playerjmr** [comment]
> I'm pretty sure it directs you to install RC24 after you do homebrew

After homebrew browser, It will ask if you want to install riiconnect24, wiilink, wiimmfi, all of which claim are optional to install, or return back to site navigation. There is no set “order” for any of them. However, one thing that was failed to be updated (not by the fault of anyone) was that some riiconnect24 channels may overwrite the wiilink ones.

**Comment by NecroNovaVGitHub** [comment]
> > We had put the wiilink discord on that guide that nova wrote, but then you reverted the entire thing. Kind of sends a distasteful message
> 
> I explained why I reverted it but as I've said I'm thinking of just linking WiiLink's page for the people which are intending to install it rather than make our own page, but I created a group DM to be sorting it out.

Im just saying, you still really shouldve discussed possibly reverting the whole thing with me BEFORE actually reverting. It kinda shows that you dont care and will instantly discard possibly great changes because of a few small things.

**Comment by Naim2000** [comment]
though really and truly it was formatted really badly. which is why i think it'd be awesome if wii.guide just redirected to wiilink's guide, like why are we maintaining 2 at once

**Comment by larsenv** [comment]
We're slowly discussing what to do with the guide to remove any kind of issue with it, but most people seem to agree that linking to WiiLink's actual site is the best idea. I don't appreciate WiiLink creating drama over this when I did try to ask Sketch if he was OK with us linking directly. Either way, history's repeated itself and this happened 5 years ago with DC24.

**Comment by Peter0x44** [comment]
My personal choice for "best option" is to remove both wiilink and rc24
Move the rc24 page to rc24.xyz and let the wiilink people do what they want

**Comment by larsenv** [comment]
Is that your idea because it gets rid of the bias?

**Comment by Peter0x44** [comment]
> Is that your idea because it gets rid of the bias?
Well, that's part of it
No one would complain about bias if this was implemented
Also rc24 and everything related to it is easily the most optional stuff on the guide

**Comment by EngineerRunner** [comment]
hey, if nobody has noticed, [wii.hacks.guide](https://wii.hacks.guide/) now exists, and it is not ran by either party.

**Comment by playerjmr** [comment]
> hey, if nobody has noticed, [wii.hacks.guide](https://wii.hacks.guide/) now exists, and it is not ran by either party.

We are all aware, thanks

**Comment by pyorot** [comment]
> > hey, if nobody has noticed, [wii.hacks.guide](https://wii.hacks.guide/) now exists, and it is not ran by either party.
> 
> We are all aware, thanks

Who is "we"? I don't think you appreciate that most people aren't even at the stage of understanding why there are seemingly two copies of the same website now.

**Comment by playerjmr** [comment]
> > > hey, if nobody has noticed, [wii.hacks.guide](https://wii.hacks.guide/) now exists, and it is not ran by either party.
> > 
> > 
> > We are all aware, thanks
> 
> Who is "we"?

By “we” I mean most of us in this conversation were involved in creating it

> I don't think you appreciate that most people aren't even at the stage of understanding why there are seemingly two copies of the same website now.

it’s relatively new, I don’t expect people to know about it right away, especially since Wii.guide has been embedded to every video guide in the corners of youtube.

**Pull request closed without merging**
