### PR TITLE
NUS is up again, so update the `update` guide accordingly

### PR DESCRIPTION
**Pull request by osfanbuff63**
https://twitter.com/OatmealDome/status/1544731705558319105

### CODE REVIEW

**Comment by larsenv** [comment]
Thanks. I was too lazy to do this.

**Comment by KcrPL** [comment]
`use the updater worked into the Wii Menu` sounds strange...

**Comment by osfanbuff63** [comment]
> `use the updater worked into the Wii Menu` sounds strange...

Do you have a suggestion otherwise? I guess I could specify the path to it, but I don't know.

**Comment by Peter0x44** [comment]
> use the updater worked into the Wii Menu 
Not only is this worded badly, but it's also a horrible idea to do blindly
It could brick you, depending how the wii was modded in the past (003 brick)
I don't approve of this, I'm going to revert it

**Comment by osfanbuff63** [comment]
That's probably a good idea, but there should be some kind of note that the NUS is up - but this is still the recommended method.

**Comment by Peter0x44** [comment]
actually, I think this might be true of the update guide also, but a step to install priiloader before rebooting should resolve the issue

**Comment by Peter0x44** [comment]
Oh, it's mentioned to do that right after, so it's fine

**Pull request merged**
