### PR TITLE
Updated link to vWii themes Guide

### PR DESCRIPTION
**Pull request by DraconicNEO**
I updated The link to a Newer vWii themes guide becuase the old Guide was outdated.

### CODE REVIEW

**Comment by Peter0x44** [comment]
Only English should have been changed here. The rest of the languages are handled by crowdin.
I'm not sure what's "outdated" about the current linked gbatem post. Do you mind elaborating here?

**Comment by DraconicNEO** [comment]
> 
> 
> Only English should have been changed here. The rest of the languages are handled by crowdin.
> I'm not sure what's "outdated" about the current linked gbatem post. Do you mind elaborating here?

I wish I had known I didn't need to do the other languages beforehand, I spent way too much time doing every single themes page... Well sorry about that, I'll try not to do it again.

Regarding how the old guide is outdated, well in recent times we have discovered that there are other, faster methods of installing themes that don't require rebooting the entire Wii U just to Change the vWii menu theme (The original method used FTPiiU so it required you to reboot). Since the newer method uses the MyMenuify CSM installer it's much faster than the previous method using FTPiiU. You still need to do all the steps beforehand to compile the themes in order to use them but afterwards assuming you keep the themes on your SD card. Also installing from a CSM manager is a simpler process than doing FTPiiU, especially for someone who has never poked around the Wii's Filesystem before.

**Comment by Peter0x44** [comment]
Is there perhaps a chance you can get this as a page on wiiu.hacks.guide? Have you discussed that with people over in nintendo homebrew?

**Comment by DraconicNEO** [comment]
> 
> 
> Is there perhaps a chance you can get this as a page on wiiu.hacks.guide? Have you discussed that with people over in nintendo homebrew?

I tried but the people in Nintendo Homebrew said that wiiu.hacks.guide's vWii section was really more meant for the basics like setting Up the basics of Homebrew on the vWii, stuff like HBC install, Nand backup, cIOS, basics. Since this is cosmetic they said that this guide didn't really fit there.

**Comment by Peter0x44** [comment]
Hm, alright
I think we could accommodate it with its own page on the guide, if that's OK with you

**Comment by DraconicNEO** [comment]
> 
> 
> Hm, alright
> I think we could accommodate it with its own page on the guide, if that's OK with you
> We already have a Wii U specific page for RiiConnect24

Sure I'm good with that.

**Comment by Peter0x44** [comment]
This is going to be implemented in a separate PR - closing this

**Pull request closed without merging**
