### PR TITLE
Create wilbrand page

### PR DESCRIPTION
**Pull request by Naim2000**
Yet to add screenshots. Also im starting to use git on the command line hoorayyyyyy

### CODE REVIEW

**Comment by JasperZebra** [comment]
> Yet to add screenshots. Also im starting to use git on the command line hoorayyyyyy

I assume there's a limit to SD card size, right?

**Comment by Naim2000** [comment]
> > Yet to add screenshots. Also im starting to use git on the command line hoorayyyyyy
> 
> I assume there's a limit to SD card size, right?

Not really. Nobody has a 2TB sd card right

**Comment by JasperZebra** [comment]
> > > Yet to add screenshots. Also im starting to use git on the command line hoorayyyyyy
> > 
> > 
> > I assume there's a limit to SD card size, right?
> 
> Not really. Nobody has a 2TB sd card right

only asking because i tired with my 512gb SD **(mind you the one i use for OG LB and it worked)** and it didn't show

**Comment by Naim2000** [comment]
Using git on the command line is actually a whole lot of fun

**Comment by Naim2000** [comment]
Rah im heading to windows 7 for a screenshot cant bother waiting until tomorrow

**Comment by Naim2000** [comment]
It crashed when i resumed from hibernation. Nevermind

**Comment by Snare-Hawk** [comment]
a few things
- i took care of this, but just to let you know, hackmii installer must be downloaded from the site directly, the [link you initially had](https://bootmii.org/get.php?file=hackmii_installer_v1.2.zip&key=02677fdfb516eddd65852add0e0c48c47bcf0865) gives an error message because of this
- is it possible to get a better quality image of the green letter? if possible, directly from the wii message board or something lol
- in the instructions when it says to open a terminal in the directory where the file was extracted, it think it may be best to add a short instruction on how to do that, either with just saying `cd balls/Wilbrand` or some shortcut, up to you

other than these things, everything looks great! good job \:3

**Comment by Naim2000** [comment]
- lol cat
- not really. i used dolphin's texture dumping for this, im pretty sure its the exact same size
tex1_144x96_9da98c69c945a533_14

- something like this doesn't exist on macos? pain. but oh well
image

**Comment by Snare-Hawk** [comment]
nice, everything looks good to me!

**Pull request merged**
