### PR TITLE
add images to wiigsc.md

### PR DESCRIPTION
**Pull request by trlandrew**

### CODE REVIEW

**Review by Naim2000 — CHANGES_REQUESTED** [review]
Err. Nice and all but I think you should upload the images to the repository itself.
Put them in a folder like `/images` (maybe `/images/wiigsc`)

**Comment by trlandrew** [comment]
> Err. Nice and all but I think you should upload the images to the repository itself. Put them in a folder like `/images` (maybe `/images/wiigsc`)

Tried but my browser crashed everytime. That's when I used ShareX to upload my images to Imgur. 🤷‍♂️

EDIT: It doesn't crash now, I'll try.

**Comment by Naim2000** [comment]
Epic, gonna test out how it looks
Also you did this on your master branch. So just hang on

**Comment by Naim2000** [comment]
Looks like you uploaded the same image twice

**Comment by Naim2000** [comment]
Okay i got this one

**Comment by Naim2000** [comment]
And now....

**Comment by Naim2000** [comment]
aand somehow it still merged a different commit and now the two branches have diverged .-.

**Pull request merged**
