### PR TITLE
Not secure link 

### PR DESCRIPTION
**Pull request by Fun4TubeGr**
I removed this link ulti larsen fix that

### CODE REVIEW

**Comment by Fun4TubeGr** [comment]
Why you close this?

**Comment by KcrPL** [comment]
1) Grammar error `(removed becose is not securce link)` should be `(remove because it's not a secure link)`
2) Well, deleting a link is not a good way to solve a problem.

**Comment by Fun4TubeGr** [comment]
Ok delete this pull request

**Comment by KcrPL** [comment]
On GitHub we can't delete Pull Request's or Issue's.

**Comment by ArtutoGamer** [comment]
I just fucking love this xDDDD

**Comment by spotlightishere** [comment]
Link looks secure to make. Thanks for closing.

On October 6, 2017 3:13:13 PM CDT, Artuto <notifications@github.com> wrote:
>I just fucking love this xDDDD
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RiiConnect24/Wii-Guide/pull/2#issuecomment-334858435

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KcrPL** [comment]
@ArtutoGamer me too lol

Spotlight, actually when you clicked on the link in wii.guide Chrome said that it was unsecure. I fixed it by hosting the WiiMC YT version on our repo.

**Comment by thejsa** [comment]
Probably filetrip brings in some stylesheets or JS over HTTP and it of course has a password input which will make Chrome flag it as insecure

**Comment by KcrPL** [comment]
We should just host files on our repo. GitHub gives us 1GB with GitHub pages.

**Comment by thejsa** [comment]
@KcrPL GitHub strongly discourage this

**Pull request closed without merging**
