### PR TITLE
create a nintendont page

### PR DESCRIPTION
**Pull request by thondorigithub1**
please correct anything if i'm wrong, i haven't used nintendont yet, so there might be corrections that are needed.

### CODE REVIEW

**Comment by Snare-Hawk** [comment]
some things i'd say to fix and that i'd mess with if i wasn't so busy procrastinating studying for finals:

- i feel like the header sizes of some headers need to be edited, i could be wrong though
- the things under key features should be an unordered list, not an ordered one
- nintendont isn't a USB loader, yet a way to load gamecube games on your wii system (or something like that, again i could just be wrong here), so i'd change the phrasing
- addition on how to set up controllers with them `controllers.ini` files ~~that of which i have no idea how to do myself lmao~~
- better phrasing on the second `{: .notice--info}` on the page and the second step of the downloading step
- add the page to the site navigation page too

balls <3

**Comment by thondorigithub1** [comment]
ok

**Comment by thondorigithub1** [comment]
i give up

**Comment by Naim2000** [comment]
> i give up

I don't........ nintendon't

**Comment by larsenv** [comment]
No offense but if you give up this easily and write silly commit names it makes me think you're young... (Plus the Roblox profile picture). There's a Nintendont page on GBAtemp, aka the OP of the master thread which has very good information.

I should really be checking these PRs more then make sure PRs are delegated to the right people that can merge them.

**Comment by thondorigithub1** [comment]
just close it, i tried, but i dont have experience with nintendont

**Pull request closed without merging**
