### PR TITLE
Add info about virtualizing bluebomb

### PR DESCRIPTION
**Pull request by Devnol**
Basically recommending the use of Live USB over virtual machines as it gets asked quite often in our server and is a very common problem people encounter.

### CODE REVIEW

**Comment by Peter0x44** [comment]
I would prefer "Live USB" as two separate words.

**Comment by Devnol** [comment]
I used to have it like that but I think LiveUSB is how most distros market it unless I'm being stupid which I probably am.

**Comment by akisblack** [comment]
Most popular distros used for this purpose (eg. Ubuntu, Pop, Mint and Fedora) use the terms "Live Ubuntu", "Live environment", "Live session" and "Live version" respectively. I think it would be better if we followed either Peter's recommendation or use the term live session and explain what it is in the guide itself.

**Comment by KcrPL** [comment]
I'm voting for `Live environment`.

**Comment by Devnol** [comment]
Yeah that's fine I can change that real quick

**Comment by Devnol** [comment]
Live environment works well, if someone googles that they get this as a result, which is pretty reasonable and explanatory:
"The live environment works entirely in your computer's RAM, writing nothing to disk. When you're done, you can reboot your computer and remove the USB drive or disc. The computer will be left exactly as it was. In essence, a live Linux system works just like a typical operating system installer." (from howtogeek(

**Comment by Peter0x44** [comment]
@Devnol I agree with this reasoning. It's definitely better than what I proposed.

**Comment by Peter0x44** [comment]
OK, no one has any objections. Merging.

**Pull request merged**
