### PR TITLE
Update for deleting-vffs page

### PR DESCRIPTION
**Pull request by Snare-Hawk**

### CODE REVIEW

**Review by osfanbuff63 — COMMENTED** [review]
Do we not have to delete the Forecast/News VFFs anymore? Usually, from what I remember, that did the trick for those issues. That's at least where this page was linked, right? I could just be out of the loop though :P

**Comment by thondorigithub1** [comment]
old guide only said to use the riiconnect24 clear tool tho, just updated the guide so it tells more

**Comment by noahpistilli** [comment]
> Do we not have to delete the Forecast/News VFFs anymore? 

Deleting VFF's only fix the FORE0000003 error. Anything else is invalid data and should trigger WC24 to redownload.

**Comment by larsenv** [comment]
I'm not sure how I feel regarding this PR.

**Comment by larsenv** [comment]
> > Do we not have to delete the Forecast/News VFFs anymore?
> 
> Deleting VFF's only fix the FORE0000003 error. Anything else is invalid data and should trigger WC24 to redownload.

No it isn't?

**Comment by larsenv** [comment]
First of all, we don't refer to the homebrew channel as "The Homebrew Channel" with quotaton marks, but that's not important. It should be marked optional to retain your mail, and there shouldn't be mentions of a video description on a text based guide. There are other grammatical fixes I want to see.

**Comment by thondorigithub1** [comment]
will fix it, thanks.

**Comment by Snare-Hawk** [comment]
i messed up when trying to make edits with my own thing and yadda yadda but i merged their commits and shit

here are the commits for reference or something:

522a3e2
7fa9f26
df3ac99
1472a75
cf8711d
9f79910
33246f8
6a2a4d0
241ce23
c5d0df5
b3ae819

**Pull request closed without merging**
