### PR TITLE
Update get-started.txt

### PR DESCRIPTION
**Pull request by GABO1423**
Changed the title to one that makes more sense. Changed the link to the vWii guide since it redirected to the English page instead of the Spanish page.
Added a notice that the alternative guides mentioned are only in English.

### CODE REVIEW

**Comment by GABO1423** [comment]
I also intend to check the pages that are in the Spanish version to make them as polished as possible. I would appreciate to discuss this with other Spanish speakers.

**Comment by Artuto** [comment]
Thanks for this! We indeed are interested in having the other pages checked (I'm the main spanish translator).

**Comment by GABO1423** [comment]
¡Hola mi buen amigo! I will begin a marathon checking every single page one at a time to make sure it looks as nice and understandable as possible (being a native Spanish speaker helps) I will try to make a note of every change done to every page.

**Comment by GABO1423** [comment]
When I'm finished, I will make another pull request.

**Comment by Artuto** [comment]
If you want you can just keep committing more changes to the same branch (patch-1) so you dont have to open multiple PRs.

**Comment by GABO1423** [comment]
Thanks for the suggestion! Wish me luck.

**Comment by fancythedeveloper** [comment]
Maybe small update for CleanRip 2.1.0?

**Comment by larsenv** [comment]
You just bumped a 5-month-old pull request. How do you feel?

**Comment by larsenv** [comment]
No progress has been made on this so I'm closing it.

**Pull request closed without merging**
