### PR TITLE
Create a "bricks" page

### PR DESCRIPTION
**Pull request by trlandrew**
As requested by playerjmr, this page will show all known bricks that can happen to a Wii. Doesn't include Error 003 brick, but a image for it exists at /images/Error003brick.png. Will make a ShowMiiWads page later when I have time.

### CODE REVIEW

**Comment by Naim2000** [comment]
Also real quick, do you mind if 90% of the file suddenly gets changed

**Comment by trlandrew** [comment]
oh great but uhh when my 2 pull requests will be merged

**Comment by Naim2000** [comment]
> oh great but uhh when my 2 pull requests will be merged

After i add delete functionality to [cdbackup](https://github.com/Naim2000/cdbackup) and when we use an app other than WML for fixing semibricks. WML is cringe

**Comment by trlandrew** [comment]
okay

**Comment by Naim2000** [comment]
[That's one down.](https://github.com/Naim2000/cdbackup/releases/tag/v1.1.0) Next up is the region changer stuff

**Comment by trlandrew** [comment]
great

**Pull request merged**
