### PR TITLE
Fix code blocks wrapping

### PR DESCRIPTION
**Pull request by NightYoshi370**
Before anyone asks, this is tested on dsi.cfw.guide

### CODE REVIEW

**Comment by Artuto** [comment]
Can you show a screenshot?

**Comment by NightYoshi370** [comment]
https://cdn.discordapp.com/attachments/547986366357700620/690699320596496394/2020-03-20_18.11.00.png
https://cdn.discordapp.com/attachments/547986366357700620/690699322739916821/2020-03-20_18.11.45.png

**Comment by KcrPL** [comment]
I mean, we've got nothing to lose lmao.

We'll revert if something breaks.

**Comment by NightYoshi370** [comment]
As I said, this is tested on dsi.cfw.guide. as such, I know it won't break things. In fact, it'll just provide enhancements. It helps for mobile users

**Comment by urmum-69** [comment]
Well, I'll test it out locally. Just want to make sure it doesn't break anything.

**Comment by urmum-69** [comment]
Works exactly as intended. Merging.

**Pull request merged**
